#!/bin/bash

ip_regex='^(?:[1-9]|[1-9][0-9]|[1-9][0-9]{2}|2[0-4][0-9]|25[0-5])\.(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.(?:[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.(?:[1-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-4])$'

check_ip_address() {
  local ip_address="$1"
  if [[ $ip_address =~ $ip_regex ]]; then
    echo "$ip_address is a valid IPv4 address"
  else
    echo "$ip_address is not a valid IPv4 address"
  fi
}
